* maven-mode

  maven-mode is a mode for emacs to make working with [[http://maven.apache.org][maven]] more fun.

** Credits

   Thanks to emacsrocks.com for inspiring me to try and write a emacs minor
   mode. 

** Keybindings

   All keybindings in maven-mode start with `C-c m` and then a two
   letter nmemonic shortcut

   - `ds` (dependency search) :: Perform a search against
        http://search.maven.org for an artifact, choose artifact from
        results, then choose a version, and then the dependency xml is
        generated and inserted into current buffer.
   - `dx` (depenedency xml) :: Good for when you know the groupId,
        artifactId and version and want to generate the dependency xml
        snippet. For example, enter `log4j:log4j:1.2.17` to generate
        dependency xml and insert it into current buffer.

** Development

   To fetch test dependencies: 

#+begin_src sh
cd /path/to/maven-mode
git submodule init
git submodule update
#+end_src   

   Run the tests with ecukes. Currently, if you run ecukes in the
   terminal, the features don't work for some reason. But if you run
   inside current emacs, they work fine. 

#+begin_src elisp
(add-to-list 'load-path "/path/to/ecukes")
(require 'ecukes)
#+end_src

   Then, open any file inside this maven-mode project and run `M-x ecukes`

** ideas for improvements

   - Add functionality to find pom.xml and find depenedency section
     and add dependencies in there (maybe by alphabetical order on artifactid?)
  
